sudo: false
language: python
python:
  - '2.7'
  - '3.4'
env:
  global:
    - DB=postgres
    - NOSE_NOLOGCAPTURE=1
  matrix:
    - DJANGO=1.6.11
    - DJANGO=1.7.7
install:
  - pip install -q coverage flake8 Django==$DJANGO
  - pip install -q django-nose psycopg2 mock south>=1.0.2 django-dynamic-fixture django-extensions
  - pip install -e .
before_script:
  - psql -c 'CREATE DATABASE narrative;' -U postgres
script:
  - flake8 .
  - coverage run manage.py test
  - coverage report --fail-under=80
